### PR TITLE
In README, apply plugin to allprojects

### PR DESCRIPTION
**Pull request by akroy**
Without this, the plugin has basically no effect.

### CODE REVIEW

**Comment by jmcampanini** [comment]
you could also apply it to each java project, right?

**Comment by akroy** [comment]
Like, instead of `allprojects`, apply to each project that has `compileJava`? Is this plugin specific to Java dependencies? (my projects are groovy, and it worked for them)

**Comment by jmcampanini** [comment]
the idea is that the plugin doesn't require you to apply it to all projects. you pick which one you want it to work on, and apply it there. this plugin works fine for the projects it has it applied too.

ideally it's applied to all projects, since it's usually used for caching purposes on CI environments, and you want to cache all your dependencies...

i could see the README stating this in a comment, right above the `allprojects` block you added.

short: the plugin has the intended effect, but the documentation should be more user friendly.

**Comment by akroy** [comment]
Apologies, yes, that's true. I just meant that following the directions as written, for most folks, the plugin has no effect. Just trying to make this easy to apply. :)

I'll tweak this to have comment to that effect, and you can see if that makes this reasonable

**Comment by akroy** [comment]
@jmcampanini I don't actually have any privileges on this repo, but I'm good with this merging whenever 💃

**Comment by jmcampanini** [comment]
i don't either. @nmiyake + @atrocities help here? :)

**Comment by nmiyake** [comment]
Enabled CI builds on forks -- once that verifies there, will merge.

**Pull request merged**
